name: Build and Deploy Image to Azure App Service via ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: 'Set up Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build and Push Image to ACR'
      run: |
        az acr build --registry ${{ secrets.ACR_NAME }} --image myapp:${{ github.sha }} .

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
