name: Build and Deploy Docker Image to Azure App Service via ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }} .

    - name: Push the Docker image to ACR
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: 'Deploy to Azure App Service from ACR'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
